<h2 class="noDisplay">Main Navigation</h2>
<div class="main-nav">
    <ul class="clearfix">
        <li>
            <a href="<?php echo $this->url(array('controller' => 'customer','action' => 'list'));?>" title="Customers">
                Customers
            </a>
        </li>
        <li>
            <a href="<?php $this->url(array('controller' => 'catalog', 'action' => 'list'));?>" title="Catalog">
                Catalog
            </a>
        </li>
        <li><a href="/" title="Homepage">Store</a></li>
        <li class="">
            <a href="<?php echo $this->url(array(
                   'controller' => 'customer',
                   'action' => 'logout',
                       ), 'default', true
               );
            ?>"
               title="Logout">Logout</a>
        </li>
    </ul>
</div>