<h2 class="noDisplay">Main Navigation</h2>
<div class="main-nav">
    <ul class="clearfix">
        <li class="current">
            <a href="
                <?= $this->url(array(
                        'controller' => 'index',
                        'action'     => 'index',
                        ), 
                        'default', true
                    ); 
                 ?>" 
               title="Homepage">Store</a>
        </li>
    </ul>
</div>