<?php
$sz_Control = Zend_Controller_Front::getInstance()
		->getRequest()
		->getControllerName();
?>
<h2 class="noDisplay">Main Navigation</h2>
<div class="main-nav">
    <ul class="clearfix">
        <li class="<?php if ($sz_Control == 'index') echo 'current' ?>">
            <a href="<?php echo $this->url(array(
				'controller' => 'index',
				'action' => 'index',
					), 'default', true
			);
			?>" 
               title="Homepage">Store</a>
        </li>

        <?php if ($this->authInfo()->isLoggedIn()): ?>
            <li class="<?php if ($sz_Control == 'customer') echo 'current' ?>">
                <a href="<?php echo $this->url(array(
                       'controller' => 'customer',
                       'action' => 'index',
                           ), 'default', true
                   );
                ?>"
                   title="Profile">Profile</a>
            </li>
            <li class="">
                <a href="<?php echo $this->url(array(
                       'controller' => 'customer',
                       'action' => 'logout',
                           ), 'default', true
                   );
                ?>"
                   title="Logout">Logout</a>
            </li>
        <?php else: ?>
            <li class="">
                <a href="<?php echo $this->url(array(
                       'controller' => 'customer',
                       'action' => 'login',
                           ), 'default', true
                   );
                ?>"
                   title="Login">Login</a>
            </li>
        <?php endif ?>
    </ul>
</div>